theme: jekyll-theme-minimal
title: Privacy Policy for Raynet Bridge App
description:
    We value your privacy. This app only processes data provided via Facebook Lead Ads forms in order to create leads in Raynet CRM.
      - Data collected: name, email, phone, and fields provided by the lead form.
      - Purpose: to insert leads into the CRM system as requested by the page owner.
      - Storage: we do not store this data permanently; it is passed directly to Raynet CRM.
      - Data Deletion:
          users may request data deletion by contacting us at: [ vajuucs@gmail.com ].



